2020-06-04 16:54:07,723 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10c0ef1d0>: Failed to establish a new connection: [Errno 51] Network is unreachable')': /v0/b924978401ae401abd55680e2a3a78d3/wd/hub/session
2020-06-04 16:54:13,804 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10c0ef8d0>: Failed to establish a new connection: [Errno 51] Network is unreachable')': /v0/b924978401ae401abd55680e2a3a78d3/wd/hub/session
2020-06-04 16:54:19,823 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10c0ef9e8>: Failed to establish a new connection: [Errno 51] Network is unreachable')': /v0/b924978401ae401abd55680e2a3a78d3/wd/hub/session
